apiVersion: v1
kind: Service
metadata:
  name: kafka-zk-ext
  namespace: namespace
spec:
  ports:
    - name: 2181-tcp
      port: 2181
      protocol: TCP
      targetPort: 2181
    - name: 9092-tcp
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    deploymentconfig: kafka-zk
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 172.29.137.44